"""user profile fields

Revision ID: 2de6a49c0e6d
Revises: e5faccb4ce4f
Create Date: 2025-09-02 04:22:51.584998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de6a49c0e6d'
down_revision: Union[str, Sequence[str], None] = 'e5faccb4ce4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('crops', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    op.drop_column('users', 'failed_logins')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('failed_logins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'crops')
    op.drop_column('users', 'location')
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
