"""added tables for the plan system plus the tables necessary to implement TBK

Revision ID: 54fff599e421
Revises: d8b2e9345f31
Create Date: 2025-11-08 17:31:15.760266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fff599e421'
down_revision: Union[str, Sequence[str], None] = 'd8b2e9345f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_url', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('token_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_token'), 'purchase_order', ['token'], unique=True)
    op.create_index(op.f('ix_purchase_order_user_id'), 'purchase_order', ['user_id'], unique=False)
    op.create_index('ix_purchase_order_user_status', 'purchase_order', ['user_id', 'status'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_user_active', 'subscription', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index('ix_subscription_user_active', table_name='subscription')
    op.drop_table('subscription')
    op.drop_index('ix_purchase_order_user_status', table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_user_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_token'), table_name='purchase_order')
    op.drop_table('purchase_order')
    # ### end Alembic commands ###
