"""small fix

Revision ID: 6950711a37cf
Revises: 4d3537fe2ade
Create Date: 2025-11-10 18:47:42.089528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6950711a37cf'
down_revision: Union[str, Sequence[str], None] = '4d3537fe2ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'payment_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_order', 'token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('purchase_order', 'token_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'token_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('purchase_order', 'token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('purchase_order', 'payment_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
