"""add user_weather_prefs table

Revision ID: 82eacc582986
Revises: 2de6a49c0e6d
Create Date: 2025-10-26 17:19:01.747228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82eacc582986'
down_revision: Union[str, Sequence[str], None] = '2de6a49c0e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_weather_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dangerous_frost_threshold', sa.Integer(), nullable=False),
    sa.Column('dangerous_temp_threshold', sa.Integer(), nullable=False),
    sa.Column('rain_mm_threshold', sa.Integer(), nullable=False),
    sa.Column('wind_kph_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_weather_prefs_id'), 'user_weather_prefs', ['id'], unique=False)
    op.create_index(op.f('ix_user_weather_prefs_user_id'), 'user_weather_prefs', ['user_id'], unique=True)
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.VARCHAR(length=10), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_weather_prefs_user_id'), table_name='user_weather_prefs')
    op.drop_index(op.f('ix_user_weather_prefs_id'), table_name='user_weather_prefs')
    op.drop_table('user_weather_prefs')
    # ### end Alembic commands ###
