"""add predictionrecord table

Revision ID: 94711edb4ff5
Revises: 2292e55836f6
Create Date: 2025-10-27 22:43:38.236094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94711edb4ff5'
down_revision: Union[str, Sequence[str], None] = '2292e55836f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('advice', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('probability', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_user_created_desc', 'prediction_record', ['user_id', 'date_created'], unique=False)
    op.create_index(op.f('ix_prediction_record_session_id'), 'prediction_record', ['session_id'], unique=False)
    op.create_index(op.f('ix_prediction_record_user_id'), 'prediction_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_record_user_id'), table_name='prediction_record')
    op.drop_index(op.f('ix_prediction_record_session_id'), table_name='prediction_record')
    op.drop_index('ix_pr_user_created_desc', table_name='prediction_record')
    op.drop_table('prediction_record')
    # ### end Alembic commands ###
